#!/usr/bin/env bash
# installing haproxy server and config

apt-get -y update
apt-get -y install haproxy

echo "\
# HAproxy Configaration for webserver
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
    balance roundrobin
    server 33989-web-01 54.87.238.0 check port 80
    server 33989-web-02 100.26.253.132 check port 80
" >> /etc/haproxy/haproxy.cfg
haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy start
service haproxy status
